### ISSUE TITLE
Mixin error  sewing-machine-1.5.1_mc-1.18.1

### ISSUE THREAD

**Issue by PCMartinzzon** [GStefanowich/MC-Server-Protection#53] opened 2022-03-12 12:56 UTC
I get errors on both modded and unmodded servers 

Here is the error log for the modded server
https://pastebin.com/vm83fzdq

**Comment by GStefanowich** [comment] 2022-03-12 14:13
This is a duplicate of #37 - Both my mod and StyledChat try to override the chat. I'll try and resolve mod conflicts when I've got more free time

Thanks for the report

**Closed as completed by GStefanowich** 2022-03-12 14:13 UTC
Labels: mod conflict
