### ISSUE TITLE
Player corpse/grave being deleted immidiately after death...

### ISSUE THREAD

**Issue by ghost** [GStefanowich/MC-Server-Protection#49] opened 2022-02-21 21:28 UTC
[14:26:56 FATAL]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.TheElm.project.objects.PlayerBackpack.dropAll(boolean)" because "this.backpack" is null
	at net.minecraft.class_1657.handler$bca000$onInventoryDrop(class_1657.java:4897) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_16078(class_1657.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_16080(class_1309.java:1372) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_6078(class_3222.java:613) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5643(class_1309.java:1177) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5643(class_1657.java:914) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_5643(class_3222.java:705) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5747(class_1309.java:1522) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5747(class_1657.java:1699) ~[server-intermediary.jar:?]
	at net.minecraft.class_2248.method_9554(class_2248.java:464) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5623(class_1297.java:1137) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5623(class_1309.java:318) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_14207(class_3222.java:1001) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12063(class_3244.java:929) ~[server-intermediary.jar:?]
	at net.minecraft.class_2828.method_12272(class_2828.java:114) ~[server-intermediary.jar:?]
	at net.minecraft.class_2828$class_2829.method_11054(class_2828.java:42) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by GStefanowich** [comment] 2022-02-23 22:42
Closing as a duplicate of #48 Will be posting a fix for this shortly

Thanks for reporting this issue

**Closed as completed by GStefanowich** 2022-02-23 22:42 UTC
