### ISSUE TITLE
[Request] Documentation for the config file.

### ISSUE THREAD

**Issue by KS-HTK** [GStefanowich/MC-Server-Protection#47] opened 2022-01-24 15:40 UTC
Some options in the config file are not very self explainatory, a bit off documentation would be great. Either in the file itself or as a md here on the Git.

**Comment by GStefanowich** [comment] 2022-01-24 17:02
Most of the config descriptions were recently [added to a CurseForge page](https://www.curseforge.com/minecraft/mc-mods/sewing-machine-utilities/pages/config).

Closing as a duplicate of #8

**Closed as completed by GStefanowich** 2022-01-24 17:02 UTC

**Comment by wereii** [comment] 2022-01-27 20:26
Would it be possible to point the Wiki tab here to that link?
Curseforge pages is the least expected place where I would be searching for wiki, at least for me.
