### ISSUE TITLE
Registry Remapping Issue

### ISSUE THREAD

**Issue by ifaith1** [GStefanowich/MC-Server-Protection#54] opened 2022-03-13 00:40 UTC
![connection lost](https://user-images.githubusercontent.com/43161366/158039863-a42e4d76-68d3-44a5-905b-a3eb68faad1a.png)

I had server management download the mod and was not able to access my server due to this issue that came up. I am using a Fabric API on a multiplayer server that is on 1.18.1

**Comment by GStefanowich** [comment] 2022-03-13 00:51
This is a duplicate of Issue #41 , can you let me know what other mods you're using (if any) and what version of Fabric API you're using? Others have had this issue, but I've been unable to reproduce it on any of my own servers.

**Comment by ifaith1** [comment] 2022-03-13 01:11
Of course! I'm using Fabric API 0.46.4 + 1.18 according to the mods name

Mods I'm using:
- Medieval Minecraft [FABRIC] - 1.18.1 modpack [[LIST OF MODS IN MODPACK](https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-fabric/relations/dependencies)]
- Worldedit
- Luckperms
- Essential Commands

**Comment by Zunwolf1896** [comment] 2022-03-26 07:24
Using fabric API 0.46.6+1.16 as well, having the same issue,

Using the mods in this mopack here: https://www.curseforge.com/minecraft/modpacks/wolfqueens-origins/files/all 

I assume this means this mod is unable to be used until a fix is found, then?

**Closed as completed** 2022-04-26 20:57 UTC
Labels: can't duplicate, mod conflict
